name: Publish Extension
on:
  push:
    branches: main
    paths:
      - "src/**"
      - ".github/workflows/main.yaml"

env:
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  API_URL: https://lambda.roamjs.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: build
        run: npx roamjs-scripts build --depot
      - name: publish
        run: npx roamjs-scripts publish --depot
